# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bytereel < Formula
  desc "ByteReel converts any file to a video"
  homepage "https://github.com/kaspar1ndustries/go-bytereel"
  version "0.205"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kaspar1ndustries/go-bytereel/releases/download/v0.205/bytereel_v0.205_darwin_arm64.tar.gz"
      sha256 "0db4aa17aece34859f2c59d96afcb36aaeedeb92e025be36f9c56db247ad6bc6"

      def install
        bin.install "bytereel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kaspar1ndustries/go-bytereel/releases/download/v0.205/bytereel_v0.205_darwin_amd64.tar.gz"
      sha256 "188f9d80e6b6b05401b1b599e9f5346bb3986a0d00500eba94cea21982982463"

      def install
        bin.install "bytereel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaspar1ndustries/go-bytereel/releases/download/v0.205/bytereel_v0.205_linux_arm64.tar.gz"
      sha256 "456b63deeee2d3c72b8a5c21d3b27f25d0700c642dd36efbbee914edcaeee8b4"

      def install
        bin.install "bytereel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kaspar1ndustries/go-bytereel/releases/download/v0.205/bytereel_v0.205_linux_amd64.tar.gz"
      sha256 "9bc6c3d71d6842fc9174705a39fbfd6f101b78159072506d862f36ecac1b3380"

      def install
        bin.install "bytereel"
      end
    end
  end

  test do
    system "#{bin}/bytereel", ""
  end
end
