# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rival < Formula
  desc "Dispatch prompts to Codex, Antigravity, and Claude CLIs from Claude Code with session tracking and TUI/web dashboard"
  homepage "https://github.com/1F47E/rival"
  version "3.14.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1F47E/rival/releases/download/v3.14.2/rival_darwin_amd64.tar.gz"
      sha256 "851d44a874875b8787f0feb8b6cdf8c4358a620f019d6396abf36aedfe7969d7"

      define_method(:install) do
        bin.install "rival"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1F47E/rival/releases/download/v3.14.2/rival_darwin_arm64.tar.gz"
      sha256 "778744266a4b0ebd9fb813a7f02844a498c96ac2779dbf605d1ff35b56738c7d"

      define_method(:install) do
        bin.install "rival"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1F47E/rival/releases/download/v3.14.2/rival_linux_amd64.tar.gz"
      sha256 "fa6ed1922d4911ba75402d19c4bf1ec8b0020bdc666b70dbeb446d92e8d00463"
      define_method(:install) do
        bin.install "rival"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1F47E/rival/releases/download/v3.14.2/rival_linux_arm64.tar.gz"
      sha256 "e83c0c5df7d6adfd24de56a75a6b3c9e5406b04cb8167aa1c5b2fafaff484a4c"
      define_method(:install) do
        bin.install "rival"
      end
    end
  end
end
