# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rival < Formula
  desc "Dispatch prompts to AI coding agents with session tracking and TUI/web dashboards"
  homepage "https://github.com/1F47E/rival"
  version "3.23.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1F47E/rival/releases/download/v3.23.0/rival_darwin_amd64.tar.gz"
      sha256 "c7d977f4c5cef7421b4a05dcc7f38ba7df28053e9dc46b384ec9a2c9e31c58b1"

      define_method(:install) do
        bin.install "rival"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1F47E/rival/releases/download/v3.23.0/rival_darwin_arm64.tar.gz"
      sha256 "c60fb4d57677d9132a3b7025c8fc10ad621f03116f8346d67a85d8cb6fa8d8f8"

      define_method(:install) do
        bin.install "rival"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1F47E/rival/releases/download/v3.23.0/rival_linux_amd64.tar.gz"
      sha256 "0bf11736f234b93f56e96d64a28eecb2401ba92f877c33ffaa73f67147c58761"
      define_method(:install) do
        bin.install "rival"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1F47E/rival/releases/download/v3.23.0/rival_linux_arm64.tar.gz"
      sha256 "df29b7fea18982ee8cceb2145c11d4ba683836f387fbd0f738a959efb3e86e67"
      define_method(:install) do
        bin.install "rival"
      end
    end
  end
end
